export function PageHeader({
  title,
  subtitle,
  action,
}: {
  title: string;
  subtitle: string;
  action?: React.ReactNode;
}) {
  return (
    <header className="glass mb-6 flex flex-wrap items-center gap-4 rounded-2xl px-5 py-4">
      <div className="min-w-0">
        <h1 className="font-display text-xl font-bold">{title}</h1>
        <p className="text-sm text-ink-subtle">{subtitle}</p>
      </div>
      <div className="ml-auto flex items-center gap-3">{action}</div>
    </header>
  );
}

export function Disclaimer() {
  return (
    <p className="glass-soft mt-6 rounded-xl px-4 py-3 text-[12px] leading-relaxed text-ink-muted">
      <span className="font-semibold text-ink">Responsible AI:</span> content here is generated by
      an on-device demo model. Review every draft for accuracy, confidentiality, bias and
      appropriateness before using it professionally — and never paste sensitive personal or
      client data into an assistant.
    </p>
  );
}
